### ISSUE TITLE
No Header in case of a partial Forward

### ISSUE THREAD

**Issue by tvnshack** [jeevatkm/ReplyWithHeader#81] opened 2015-03-24 10:18 UTC
Hello,

If you select one part of a mail to forward it to some other distribution list, there is no Header at all. Nothing. Apple Mail without RWH sets a (short) Header in this case. I would expect RHW to generate a full Header, as if the Forward mail was composed without first selecting lines of the original mail.

This is quite a regression from the situation without RWH as we're loosing the possibility to easily forward one selected set of lines among a (sometime very long chain of) mail.

Thanks for addressing this issue appropriately.

**Comment by jeevatkm** [comment] 2015-04-02 01:54
Sure, I will address this issue in upcoming release.

**Comment by jeevatkm** [comment] 2015-05-29 19:22
I have followed your instruction to reproduce. However I'm unable to replicate. May be I'm missing something.

Attaching few screenshots for your reference (as per steps described - [https://github.com/jeevatkm/ReplyWithHeader/issues/80#issuecomment-106713268](https://github.com/jeevatkm/ReplyWithHeader/issues/80#issuecomment-106713268)). Can you help me to find an issue, once I have root cause; will be able to address that. Also can you share details of OS X version and Mail.app version too.

![screen shot 2015-05-29 at 12 11 08 pm](https://cloud.githubusercontent.com/assets/1175977/7890785/f6091c00-05fc-11e5-8337-6443e70c7b25.png)
![screen shot 2015-05-29 at 12 11 29 pm](https://cloud.githubusercontent.com/assets/1175977/7890789/ffa02c40-05fc-11e5-910f-7321fcb3b5b7.png)
![screen shot 2015-05-29 at 12 12 06 pm](https://cloud.githubusercontent.com/assets/1175977/7890793/07123e00-05fd-11e5-955a-3f0dcbf494ea.png)

**Comment by jeevatkm** [comment] 2015-06-02 02:46
@tvnshack - Can you provide inputs for above comments? Since I'm planning to wrap up the v5.0 development. Thanks!

**Comment by jeevatkm** [comment] 2015-08-13 02:25
As of now, didn't received an inputs. so closing it for now.

**Closed by jeevatkm** 2015-08-13 02:25 UTC
Labels: analyze, enhancement
