### ISSUE TITLE
Issues with having the header below the text

### ISSUE THREAD

**Issue by NX70** [jeevatkm/ReplyWithHeader#95] opened 2016-01-07 09:12 UTC
In very rare circumstances it happens that the header is below the text.
That happens only when using "reply", if I "forward" the same eMail it's all correct.

If I switch off RHW, I get the original reply line from Mail above the text, as it should be.

I'm using 5.1-beta

**Comment by jeevatkm** [comment] 2016-01-07 20:13
Thanks for reporting an issue. Could you please provide me with sample emails, so I can do testing at my end and find a way to address them?

**Comment by ziggyke** [comment] 2017-04-01 12:05
I can't reproduce this problem with RWH v5.2 and not even with v5.3 beta.
So until someone can handover jeevatkm some examples this won't/can't be fixed.

**Comment by jeevatkm** [comment] 2017-12-03 04:32
@ziggyke Thank you for your research. I'm closing this and also moving towards #113.

**Closed by jeevatkm** 2017-12-03 04:32 UTC
Labels: analyze
