### ISSUE TITLE
[BUG] v6.0: Preferences plugin GUI not working: High Sierra 10.13.6

### ISSUE THREAD

**Issue by JayBrown** [jeevatkm/ReplyWithHeader#116] opened 2018-10-21 22:46 UTC
The mail plugin itself seems to work: it does change the header, but the plugin settings are not accessible in Apple Mail preferences, i.e. there's no way to configure it, at least not from the GUI.

High Sierra 10.13.6

**Comment by jeevatkm** [comment] 2018-10-22 04:41
@JayBrown RWH preferences UI moved to main menu(look for RWH menu). I have mentioned in the release notes/changelog. 

Background: Due to Mail.app internal changes. RWH preferences UI was cut off in Mail preferences, so it have been moved to main menu.

This is not a bug.

**Comment by JayBrown** [comment] 2018-10-22 09:38
Yeah, that was the weird thing. I knew about this, but the RWH menu didn't show up after first install. (Had to try several times; see below.) So I figured that was for Mojave only, not for High Sierra. I just did a fresh install, and this time the RWH menu appeared.

Can't say what went wrong the first time. Maybe it's because I didn't remove the quarantine xattr before installing? I did get the error message that RWH wasn't compatible with Mail 11.15 when Mail launched. So I re-installed ("updated") using the command file: same error messagen; then I removed the bundle from and reinstalled into the Mail directory manually, and then Apple Mail launched without errors, but the RWH menu wasn't there.

Only worked after a clean install, fresh download, unquarantine before installation etc.

**Comment by JayBrown** [comment] 2018-10-22 09:48
It finally worked, but only after a clean install. The first time around there was no "RWH" menu, so I thought this was for Mojave only. Don't know what went wrong. Maybe it's because I didn't remove the quarantine xattr from the downloaded files before installing? I tried running the .command again, but Mail complained at launch that RWH wasn't compatible with Mail 11.15. Then tried installing manually, and Mail launched fine, but RWH wasn't accessible (no menu). Only a clean install with new download (including unquarantine) and installation using the .command helped.

**Comment by jeevatkm** [comment] 2018-10-22 14:36
Nice its working for you. That's really wired it didn't worked for you in first or second go. My best guess is individual machine permission related issue.

RHW v6.0 is High Sierra and above. Since mail preferences UI cut started on OS High Sierra onwards. I couldn't find a way to fix within mail preferences way (that's why I didn't release v5.4 at all). Then I have decided to move the RWH preferences out of mail preferences and made it separate in RWH v6.0.

I'm closing this one.

**Closed by jeevatkm** 2018-10-22 14:36 UTC
Labels: support
