### ISSUE TITLE
Overzealous Reply All 

### ISSUE THREAD

**Issue by bstempel** [jeevatkm/ReplyWithHeader#110] opened 2017-04-25 02:53 UTC
On Sierra (10.12.4) with RWH v5.3, I'm seeing two unfortunate behaviors:

1) When I "Reply All" from within an e-mail, I'm always being copied even though I have not selected the checkbox to automatically Cc: myself. I do not see this behavior when I "Reply All" from the mailbox/preview view, nor do I see it if I uninstall RWH.

2) Even if I disable RWH from the mail.app preference pane, I see the behavior described in 1.

Thanks for taking a look!

**Comment by jeevatkm** [comment] 2017-04-25 04:43
Thanks for verifying it. Nice issue subject name :) Seems like Mail.app is doing more wonderful. 

Can you please help me to confirm? 
* Is this happening without RWH installed?
* Is this happening for all email addresses or only email aliases?

**Comment by bstempel** [comment] 2017-04-25 05:20
No, it stops if I uninstall RWH.

I have no aliases - this is for an Exchange account.

Thanks!

**Comment by tholstro** [comment] 2017-04-25 10:59
Ahhh.. I too experience this and didn't realize this was caused by RWH. You're right. Thank you bstempel!

**Comment by jeevatkm** [comment] 2017-04-25 17:12
Hmm, @bstempel @tholstro Looks like I have to trace the issue.

Thanks for letting me know.

**Comment by marcodome** [comment] 2017-04-26 16:17
Hi, I experienced this problem too: what can do to trace the issue?

**Comment by jeevatkm** [comment] 2017-04-26 16:55
@marcodome Can you help me to reproduce this issue with steps? so that I can follow the same steps to find the root cause and fix it.

Thing is I have Gmail, iCloud, and Zoho mail server with my own domain email accounts configured in my Mail.app. This issue is not happening frequently (does happen occasionally). So I'm having difficulty to figure the problem.

**Comment by marcodome** [comment] 2017-04-27 08:10
So far, it seems that it happens always in both these conditions:
- I open the email and I reply to all from within an e-mail (it doesn't happen if "Reply All" from the mailbox/preview view)
- I'm in "To:" in the received email: it does not happen if I'm in "Cc:"

I have just 1 account configured, in Outlook365.
I have also UniversalMailer plugin installed but it isn't enabled (and it hasn't been enabled since long time).

**Comment by jeevatkm** [comment] 2017-04-29 18:02
@marcodome Thank you very much for your analysis. Let me put log statement and follow your instruction to find the problem.

**Comment by bstempel** [comment] 2017-04-29 18:20
Note that the first bullet in marcodome's description matches my observation from the original post:

> When I "Reply All" from within an e-mail, I'm always being copied even though I have not selected the checkbox to automatically Cc: myself. I do not see this behavior when I "Reply All" from the mailbox/preview view


I had not observed the relationship between To: and Cc:, but I can confirm it.

**Comment by marcodome** [comment] 2017-04-29 21:10
@bstempel Yes, I used the same words of your post: they were very clear (at least to me!), so I thought that reusing was the best choice

**Comment by jeevatkm** [comment] 2017-04-29 21:36
@bstempel @marcodome Thank you, let me do my debug to find out the problem and get back to you guys.

**Comment by mshahat** [comment] 2017-05-20 11:20
Same symptoms here ... any resolution expected soon ?

**Comment by jeevatkm** [comment] 2017-05-22 18:54
@mshahat Yes, I will make it.

**Comment by bstempel** [comment] 2017-06-14 03:07
@jeevatkm, any estimate on when a fix will be available? Anything we can do to help you debug? Thanks!

**Comment by jeevatkm** [comment] 2017-06-14 03:20
@bstempel I have started the work week ago then I got occupied with my day job. Thank you for your patience. 

May be in a week or two I will do it.

**Comment by bstempel** [comment] 2017-06-14 03:21
Understood...thanks for the update!

**Comment by jeevatkm** [comment] 2017-06-15 21:59
@bstempel @mshahat @marcodome Need help for testing the fix.

Download link for v5.4-beta: http://bit.ly/2suSfId

**Comment by mshahat** [comment] 2017-06-18 14:19
Hi, thanks for that. 

If i receive an email with reply-to , reply-to-all doesn't behave right, reply only gets the right address. 

otherwise, looks good to me. well done. 

/Mo

**Comment by jeevatkm** [comment] 2017-06-18 20:39
@mshahat Thanks for verifying the fix.

> If i receive an email with reply-to , reply-to-all doesn't behave right

Can you please explain in detail about this?

**Comment by mshahat** [comment] 2017-06-23 11:03
send an email to your self with reply-to another email , if you do reply-all it won't work as expected. 

also, reply-all still not working fine after the 5.4-beta ;(

**Comment by jeevatkm** [comment] 2017-06-23 19:07
> send an email to your self with reply-to another email , if you do reply-all it won't work as expected.

I will debug this to see what happening?

> reply-all still not working fine after the 5.4-beta ;(

Do you mean above reply-to header scenario or some other scenario?

**Comment by mshahat** [comment] 2017-06-23 21:17
Hi Jeeva, for the second point, it's the reported issue here. I think beta is not solving it, it's still taking place. will try to focus more over the next couple of days, to see if i can predict a pattern. Thanks,

**Comment by jeevatkm** [comment] 2017-06-23 21:19
@mshahat Thanks, I look forward to your inputs. In the mean time I will analyze the reply-to header scenario.

**Comment by mshahat** [comment] 2017-07-16 12:34
so far, the issue of reply to ( including own email ) is still there ... do you need any log to analyse ? thanks

**Comment by jeevatkm** [comment] 2017-12-03 04:29
I have done improvements also moving towards #113, thank you :)

**Closed by jeevatkm** 2017-12-03 04:29 UTC
Labels: bug
