### ISSUE TITLE
v5 - Doesn't seem to honour email aliases with reply all

### ISSUE THREAD

**Issue by MrO007** [jeevatkm/ReplyWithHeader#89] opened 2015-07-12 18:07 UTC
Hello,

I have two email address for my account.  With RWH installed, when email is received on the second address and then clicking "reply all", the second address is left in the To: field.

With RWH removed, this doesn't seem to happen.

Cheers,

**Comment by jeevatkm** [comment] 2015-07-12 18:40
We have a look and let you know.

**Comment by jeevatkm** [comment] 2015-08-22 06:06
Found root cause and apple internal API to figure out email aliases. Will be applying fix.

**Comment by jeevatkm** [comment] 2015-08-22 06:40
@MrO007 - I have created [v5.1-beta bundle](http://bit.ly/1LouEKr), can you please try and share your feedback? then I will make v5.1-beta for public. v5.1 will be released along with EL caption release. Since Beta releases breaks the mail bundle.

**Comment by jeevatkm** [comment] 2015-08-24 17:43
@MrO007 - did you get a chance to try out beta version?

**Comment by jeevatkm** [comment] 2015-08-27 21:18
Releasing updated v5.1-beta http://bit.ly/1LouEKr.

**Closed by jeevatkm** 2015-08-27 21:18 UTC
Labels: bug

**Comment by MrO007** [comment] 2015-08-27 21:24
Hello Jeevatkm, apologies, I replied to theis before and it didn't seem to get here.  5.1-Beta didn't fix the the second alias showing after Reply All.

**Comment by jeevatkm** [comment] 2015-08-27 21:28
Actually I have addressed reply-all in the latest v5.1-beta build today. Can you take latest one and try once again?

If still persist, can you please provide me a detailed scenario, I'm happy to addressed that.

**Comment by MrO007** [comment] 2015-08-27 21:31
I downloaded and installed the file you uploaded just a minute ago.

Exchange account - multiple aliases - primary and secondary.

Email sent to the second alias.

Reply-all on the email, second alias appears in To: field.

**Comment by jeevatkm** [comment] 2015-08-27 21:35
Thanks for taking latest one. 

As asked in the date format issue, shall we have screen share to sort this one too. May be during a weekend would be helpful.

**Comment by MrO007** [comment] 2015-10-31 12:43
Hello, I'm still having an issue with Reply All.  Do you want to screen share to take a look?

Cheers,
Mike

**Comment by jeevatkm** [comment] 2015-10-31 21:04
This is interesting. Could you please provide screenshot and if any errors info in the console.app for Mail.app?
