### ISSUE TITLE
Problems with locale IT (Italian)

### ISSUE THREAD

**Issue by pmarkez** [jeevatkm/ReplyWithHeader#98] opened 2016-09-16 23:04 UTC
RWH 5.2 beta gets disabled under MacOS Sierra GM running Italian language.

**Comment by jeevatkm** [comment] 2016-09-16 23:06
Do you see any RWH message in console.app while starting Mail.app?

**Comment by sharklasergithub** [comment] 2016-09-16 23:27
I get a warning window:
**Warning: ReplyWithHeader v5.2-beta**
ReplyWithHeader v5.2-beta is currently not supported in your Locale[ italiano (Italia)(it-IT) ] it may not work as expected, so disabling it.
Please contact plugin author - https://github.com/jeevatkm/ReplyWithHeader/issues.

This is what Console reads:
Sep 17 01:24:01 MacBook-Pro-di-PM com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Sep 17 01:24:02 MacBook-Pro-di-PM Mail[12957]: ReplyWithHeader v5.2-beta plugin loaded, OS X Versione 10.12 (Build 16A320)
Sep 17 01:24:02 MacBook-Pro-di-PM Mail[12957]: ReplyWithHeader v5.2-beta debug log enabled: NO
Sep 17 01:24:02 MacBook-Pro-di-PM Mail[12957]: WARNING :: ReplyWithHeader v5.2-beta is currently not supported in your Locale[ italiano (Italia)(it-IT) ] it may not work as expected, so disabling it.
	Please contact plugin author - https://github.com/jeevatkm/ReplyWithHeader/issues.
Sep 17 01:24:10 MacBook-Pro-di-PM Mail[12957]: ReplyWithHeader plugin is disabled in mail preferences
Sep 17 01:24:14 MacBook-Pro-di-PM com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Sep 17 01:24:22 --- last message repeated 1 time ---
Sep 17 01:24:22 MacBook-Pro-di-PM diagnosticd[239]: System mode client started - Console (12963) - mode: 0x8
Sep 17 01:24:28 MacBook-Pro-di-PM Console[12963]: BUG in libdispatch client: kevent[EVFILT_VNODE] monitored resource vanished before the source cancel handler was invoked

**Comment by jeevatkm** [comment] 2016-09-16 23:30
Excepted msg.

Looks like I need to add support for `it-*` locales. Will do.

**Comment by ziggyke** [comment] 2016-09-21 13:23
I've the same error as but for a different language:
**Warning: ReplyWithHeader v5.2-beta**
ReplyWithHeader v5.2-beta is currently not supported in your Locale[ Nederlands (België)(nl-NL) ] it may not work as expected, so disabling it.
Please contact plugin author - https://github.com/jeevatkm/ReplyWithHeader/issues.

Maybe instead adding support for every locales you can add an if not localize use English instead or something like that?

Thanks for the great plugin and support!

**Comment by jeevatkm** [comment] 2016-09-21 16:28
@ziggyke I like your suggestion. Initially plugin use to fallback to `english`, however it gave unexpected behavior, some how it break elsewhere (while reply or forward). That's why I have started logging `warn` message.

I will add support for all `nl-*` in next release. thanks for using RWH.

**Comment by Mawerix** [comment] 2016-09-22 08:25
It would be great if you could add support for Swedish ;-)
ReplyWithHeader v5.2-beta is currently not supported in your Locale[ svenska (Sverige)(sv-SE) ] it may not work as expected, so disabling it.
Please contact plugin author - https://github.com/jeevatkm/ReplyWithHeader/issues.

**Comment by ziggyke** [comment] 2016-09-22 08:27
Thx jeevatkm for the reply, I'll wait with patience to the next release...

**Comment by frank-zhgj** [comment] 2016-09-22 09:04
It would be great if you could add support for Chinese ;-)

**Comment by jeevatkm** [comment] 2016-09-22 14:13
@Mawerix - Sure I will add support for `sv-*`

@frank-zhgj - RWH already has support for `zh-Hans` & `zh-Hant` locale, do you face any issues?

**Comment by frank-zhgj** [comment] 2016-09-26 05:12
@jeevatkm 

Warning: ReplyWithHeader v5.2-beta

ReplyWithHeader v5.2-beta is currently not supported in your Locale[ 中文（简体、中国）(zh-Hans-CN) ] it may not work as expected, so disabling it.
Please contact plugin author - https://github.com/jeevatkm/ReplyWithHeader/issues.

**Comment by jeevatkm** [comment] 2016-09-26 15:21
@frank-zhgj now I understand the problem, thanks. Overall OS Sierra has improved the localization implementation.

So I will have make all the implemented locale in to `locale-*` check.
```
de-*
en-*
es-*
fr-*
it-*
ja-*
ko-*
nb-*
nl-*
pt-BR-*
pt-PT-*
pt-*
ru-*
sv-*
uk-*
zh-Hans-*
zh-Hant-*
```

After these changes I will release `v5.2`.

**Comment by ziggyke** [comment] 2016-09-26 15:51
w00t, that would be great. Because now plugin isn't loaded and I'm stuck with the auwfull reply/forward headers! :'-(

**Comment by jeevatkm** [comment] 2016-09-26 17:02
I will do ASAP v5.2 release.

**Comment by Mawerix** [comment] 2016-09-30 13:34
Great! Can I find a zip with v5.2 anywhere?

**Comment by jeevatkm** [comment] 2016-09-30 13:58
@Mawerix v5.2 is not released yet, I'm working on it!

**Comment by sharklasergithub** [comment] 2016-10-04 20:24
Any way we can alter the 5.2 beta our own to get it working, while you're preparing the final public release?
Sorry for the silly question, I'm not a developer. Only tired of seeing the ugly Apple Mail headers...

**Comment by jeevatkm** [comment] 2016-10-04 21:36
@sharklasergithub I completely understand. I will make an release as soon as possible. Thanks for your patience. I appreciate it.

**Comment by ziggyke** [comment] 2016-10-19 07:25
As workaround you can do this:
Install [languageswitcher app](http://www.tj-hd.co.uk/en-gb/languageswitcher/) for changing the localization of the mail.app to English (if wanted you can configure it that it always open in English.

Then you need to go to:
Mail -> Preferences -> RWH -> enable it (your previous settings remain untouched)

If that s set when you perform a reply (all)/Forward then the headers are still in the correct language of your overal system.

Hopefully this will help others and maybe jeevatkm to pin point where the issue might be to solve it.
I was sick of not getting my beautiful headers, that I tried this methode and it works for me.

**Comment by jeevatkm** [comment] 2016-10-20 02:56
@ziggyke Thanks for workaround. This weekend I will make a release v5.2. 

To All RWH users - Thanks for your patience.

**Comment by jeevatkm** [comment] 2016-10-20 03:25
Done! will be released in v5.2 this weekend, for now updating v5.2-beta. you can download it right away.

**Comment by pmarkez** [comment] 2016-10-21 21:24
Thank you. RWH 5.2 beta updated, now is working back under macOS Sierra.

There’s only a small glitch in the date formatting: looks like now RWH always uses English formatting for the “Sent” header (“Inviata” in Italian), and it only translates some words in Italian.

Before macOS Sierra, RWH correctly used the format of the language set in the system. Now it always writes the date with the English convention and it only translates the month and day names.

Below an example of the date **_26th May 2016 3:51:54 PM_**

**1. Before macOS Sierra** (date in Italian format i.e. dd month year hh:mm:ss in 24 hour)
**Inviata:** 26 maggio 2016 15:51:54 CEST

**2. Now, under macOS Sierra** (day and month traslated in Italian, but date in English format.)
**Inviata:** giovedì, mag 26, 2016 at 3:51:54 PM

Hope I was clear. Thanks for your support in restoring the previous functionality!

**Comment by jeevatkm** [comment] 2016-10-23 23:11
@pmarkez I understand, I have changes for another user request. I will be reverting those changes for v5.2 release and created separate issue #104 for that.

**Comment by jeevatkm** [comment] 2016-10-23 23:43
Closing it for v5.2 release.

**Closed by jeevatkm** 2016-10-23 23:43 UTC
Labels: enhancement
